source_cm = ['Blood Stream',
                'Body of Water/Movement',
                'Food',
                'Obesity',
                'Parasite',
                'Disease',
                'Disease/Emotion Experiencer',
                'Disease/Medicine',
                'Disease/Medicine/Physical Burden',
                'Downward Movement',
                'Downward Movement/Medicine',
                'Medicine',
                'Medicine/Physical Burden',
                'Natural Physical Force/Physical Harm/Protection',
                'Physical Burden',
                'Physical Harm',
                'Physical Location/Protection/Natural Physical Force',
                'Protection',
                'Addiction',
                'Confinement',
                'Confinement/Physical Harm',
                'Contamination',
                'Contamination/Crime',
                'Crime',
                'Crime/Physical Harm',
                'Disease/Physical Burden',
                'Downward Movement/Physical Burden',
                'Emotion Experiencer',
                'Monster',
                'Natural Physical Force',
                'Natural Physical Force/Physical Harm',
                'Physical Harm/Protection',
                'Physical Harm/War',
                'Physical Harm/Weakness',
                'Resource',
                'Struggle',
                'Struggle/War',
                'War',
                'Animal',
                'Building',
                'Building/Downward Movement',
                'Competition',
                'Contamination/Physical Harm',
                'Crime/Contamination',
                'Game/Struggle',
                'Life Stage',
                'Natural Physical Force/Protection',
                'Physical Harm/Struggle/War',
                'Protection/Struggle',
                'Rule Enforcer',
                'Abyss',
                'Animal/Plant/Science',
                'Backward Movement',
                'Backward Movement/War',
                'Barrier',
                'Crop',
                'Forward Movement',
                'Forward Movement/Journey',
                'Journey',
                'Movement',
                'Abyss/Low Location',
                'Barrier/Building',
                'Barrier/Game',
                'Confinement/Enslavement',
                'Hazardous Geographic Feature',
                'Machine/Vehicle',
                'Portal',
                'Physical Location/Upward Movement',
                'Pathway',
                'Vehicle',
                'Competition/Game',
                'Game',
                'Competition/Game/War',
                'Competition/Struggle',
                'Game/Science',
                'Science',
                'Disease/Physical Harm',
                'Competition/Game/Struggle',
                'Downward Movement/Struggle',
                'Competition/Struggle/War',
                'Family',
                'Physical Location',
                'Accident/Physical Harm',
                'Competition/War',
                'Game/War',
                'A God',
                'Enslavement',
                'Servant',
                'A God/Enslavement/Servant',
                'Enslavement/Crime',
                'Enslavement/Leader',
                'Resource/Theft',
                'Business',
                'Business/Servant',
                'Crop/Factory',
                'Factory',
                'Machine',
                'Business/Resource',
                'Factory/Resource',
                'Building/Natural Physical Force',
                'Building/Strength',
                'Movement/Upward Movement',
                'Shape',
                'Strength',
                'Barrier/Protection',
                'Body of Water',
                'Body of Water/Energy',
                'Confinement/Struggle',
                'Energy',
                'Energy/Machine',
                'Forceful Extraction',
                'Forceful Extraction/Resource',
                'Disease/Movement',
                'Upward Movement',
                'Upward Movement/Movement',
                'Crime/Theft',
                'Theft',
                'Human Body',
                'A Right',
                'Emotion Experiencer/Monster',
                'Building/Science',
                'A God/Story',
                'Story',
                'Crop/Plant',
                'Plant',
                'Animal/Physical Harm',
                'Abyss/Downward Movement',
                'Darkness',
                'Light',
                'Low Location',
                'High Location',
                'High Location/Light',
                'Body of Water/Natural Physical Force',
                'Fire',
                'Fire/Light',
                'Clothing',
                'Human Body/Physical Harm',
                'Temperature']