wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1666425255
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      4: 3.9.15
      5: 0.12.19
      6: 4.18.0
      8:
      - 4
      - 5
